import { sqliteTable, integer, text, real } from 'drizzle-orm/sqlite-core';

export const congregations = sqliteTable('congregations', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  name: text('name').notNull(),
  city: text('city').notNull(),
  state: text('state').notNull(),
  address: text('address'),
  isHeadquarters: integer('is_headquarters', { mode: 'boolean' }).default(false),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
});

export const users = sqliteTable('users', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  password: text('password').notNull(),
  originalPassword: text('original_password'),
  phone: text('phone'),
  role: text('role').notNull(),
  congregationId: integer('congregation_id').references(() => congregations.id),
  approved: integer('approved', { mode: 'boolean' }).default(false),
  hasGeneralAccess: integer('has_general_access', { mode: 'boolean' }).default(false),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
});

export const members = sqliteTable('members', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  congregationId: integer('congregation_id').references(() => congregations.id).notNull(),
  name: text('name').notNull(),
  cpf: text('cpf').unique(),
  rg: text('rg'),
  birthDate: text('birth_date').notNull(),
  age: integer('age'),
  sex: text('sex').notNull(),
  maritalStatus: text('marital_status'),
  spouse: text('spouse'),
  email: text('email'),
  phone: text('phone').notNull(),
  address: text('address'),
  cep: text('cep'),
  neighborhood: text('neighborhood'),
  city: text('city'),
  state: text('state'),
  position: text('position').notNull(),
  baptismDate: text('baptism_date'),
  memberSince: text('member_since'),
  photoUrl: text('photo_url'),
  memberLevelId: integer('member_level_id').references(() => memberLevels.id),
  status: text('status').notNull().default('ativo'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
});

export const settings = sqliteTable('settings', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  churchName: text('church_name').notNull(),
  acronym: text('acronym').notNull(),
  email: text('email').notNull(),
  phone: text('phone').notNull(),
  address: text('address'),
  city: text('city'),
  state: text('state'),
  language: text('language').default('pt-BR'),
  currency: text('currency').default('BRL'),
  emailNotifications: integer('email_notifications', { mode: 'boolean' }).default(true),
  smsNotifications: integer('sms_notifications', { mode: 'boolean' }).default(false),
    pushNotifications: integer('push_notifications', { mode: 'boolean' }).default(true),
    whatsappNotifications: integer('whatsapp_notifications', { mode: 'boolean' }).default(false),
    birthdayReminders: integer('birthday_reminders', { mode: 'boolean' }).default(true),
  eventReminders: integer('event_reminders', { mode: 'boolean' }).default(true),
  financialReports: integer('financial_reports', { mode: 'boolean' }).default(true),
  updatedAt: text('updated_at').notNull(),
});

export const events = sqliteTable('events', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  congregationId: integer('congregation_id').references(() => congregations.id).notNull(),
  title: text('title').notNull(),
  description: text('description').notNull(),
  startDate: text('start_date').notNull(),
  startTime: text('start_time').notNull(),
  endDate: text('end_date').notNull(),
  endTime: text('end_time').notNull(),
  day1Date: text('day1_date'),
  day1Time: text('day1_time'),
  day2Date: text('day2_date'),
  day2Time: text('day2_time'),
  day3Date: text('day3_date'),
  day3Time: text('day3_time'),
  location: text('location'),
  mediaUrl: text('media_url'),
  mediaType: text('media_type'),
  category: text('category'),
  attendance: integer('attendance'),
  createdBy: integer('created_by').references(() => users.id),
  status: text('status').notNull().default('ativo'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
});

export const userApprovals = sqliteTable('user_approvals', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  userId: integer('user_id').references(() => users.id).notNull(),
  status: text('status').notNull().default('pendente'),
  requestedAt: text('requested_at').notNull(),
  approvedBy: integer('approved_by').references(() => users.id),
  approvedAt: text('approved_at'),
  rejectionReason: text('rejection_reason'),
});

export const memberPermissions = sqliteTable('member_permissions', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  memberId: integer('member_id').references(() => members.id),
  userId: integer('user_id').references(() => users.id),
  permissionKey: text('permission_key').notNull(),
  granted: integer('granted', { mode: 'boolean' }).default(true),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
});

export const transactions = sqliteTable('transactions', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  congregationId: integer('congregation_id').references(() => congregations.id).notNull(),
  type: text('type').notNull(),
  category: text('category').notNull(),
  amount: real('amount').notNull(),
  date: text('date').notNull(),
  description: text('description'),
  paymentMethod: text('payment_method'),
  accountId: text('account_id'),
  titheGiverName: text('tithe_giver_name'),
  createdBy: integer('created_by').references(() => users.id),
  status: text('status').notNull().default('ativo'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
});

export const sermons = sqliteTable('sermons', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  congregationId: integer('congregation_id').references(() => congregations.id).notNull(),
  title: text('title').notNull(),
  preacher: text('preacher').notNull(),
  date: text('date').notNull(),
  duration: text('duration'),
  category: text('category'),
  description: text('description'),
  mediaUrl: text('media_url'),
  mediaType: text('media_type'),
  thumbnailUrl: text('thumbnail_url'),
  views: integer('views').default(0),
  downloads: integer('downloads').default(0),
  createdBy: integer('created_by').references(() => users.id),
  status: text('status').notNull().default('ativo'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
});

export const communityPosts = sqliteTable('community_posts', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  congregationId: integer('congregation_id').references(() => congregations.id).notNull(),
  userId: integer('user_id').references(() => users.id).notNull(),
  type: text('type').notNull(),
  title: text('title').notNull(),
  content: text('content').notNull(),
  prayersCount: integer('prayers_count').default(0),
  likesCount: integer('likes_count').default(0),
  commentsCount: integer('comments_count').default(0),
  status: text('status').notNull().default('ativo'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
});

export const assets = sqliteTable('assets', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  congregationId: integer('congregation_id').references(() => congregations.id).notNull(),
  name: text('name').notNull(),
  category: text('category').notNull(),
  subcategory: text('subcategory'),
  location: text('location'),
  propertyType: text('property_type'),
  acquisitionDate: text('acquisition_date'),
  acquisitionValue: real('acquisition_value'),
  currentValue: real('current_value'),
  condition: text('condition'),
  description: text('description'),
  serialNumber: text('serial_number'),
  photoUrl: text('photo_url'),
  status: text('status').notNull().default('ativo'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
});

export const banners = sqliteTable('banners', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  title: text('title').notNull(),
  description: text('description'),
  imageUrl: text('image_url').notNull(),
  linkUrl: text('link_url'),
  order: integer('order').default(0),
  active: integer('active', { mode: 'boolean' }).default(true),
  startDate: text('start_date'),
  endDate: text('end_date'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
});

export const userCongregationAccess = sqliteTable('user_congregation_access', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  userId: integer('user_id').references(() => users.id).notNull(),
  congregationId: integer('congregation_id').references(() => congregations.id).notNull(),
  accessLevel: text('access_level').notNull(),
  grantedAt: text('granted_at').notNull(),
  grantedBy: integer('granted_by').references(() => users.id),
});

export const memberLevels = sqliteTable('member_levels', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  name: text('name').notNull(),
  description: text('description'),
  level: integer('level').notNull(),
  active: integer('active', { mode: 'boolean' }).default(true),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
});