import { db } from '@/db';
import { events } from '@/db/schema';

async function main() {
    const sampleEvents = [
        {
            congregationId: 1,
            title: 'Culto de Celebração - Domingo',
            description: 'Culto de adoração e louvor com pregação da Palavra. Venha celebrar conosco a bondade de Deus e compartilhar momentos de comunhão.',
            startDate: '2024-03-03',
            startTime: '10:00',
            endDate: '2024-03-03',
            endTime: '12:00',
            location: 'Templo Central - Sede Atibaia',
            mediaUrl: null,
            mediaType: null,
            category: 'culto',
            attendance: 180,
            createdBy: 1,
            status: 'ativo',
            createdAt: new Date('2024-02-15T10:00:00').toISOString(),
            updatedAt: new Date('2024-02-15T10:00:00').toISOString(),
        },
        {
            congregationId: 1,
            title: 'Estudo Bíblico Semanal',
            description: 'Estudo aprofundado do livro de Romanos. Momento de reflexão e aprendizado sobre as doutrinas fundamentais da fé cristã.',
            startDate: '2024-03-06',
            startTime: '19:30',
            endDate: '2024-03-06',
            endTime: '21:00',
            location: 'Salão de Estudos - Sede Atibaia',
            mediaUrl: null,
            mediaType: null,
            category: 'estudo',
            attendance: 65,
            createdBy: 2,
            status: 'ativo',
            createdAt: new Date('2024-02-10T14:30:00').toISOString(),
            updatedAt: new Date('2024-02-10T14:30:00').toISOString(),
        },
        {
            congregationId: 2,
            title: 'Reunião de Jovens - Jarinu',
            description: 'Encontro dos jovens com louvor, mensagem e dinâmicas. Tema: "Vivendo a fé na prática". Um momento especial para os jovens buscarem a Deus.',
            startDate: '2024-03-08',
            startTime: '19:00',
            endDate: '2024-03-08',
            endTime: '21:30',
            location: 'Congregação Jarinu',
            mediaUrl: null,
            mediaType: null,
            category: 'jovens',
            attendance: 45,
            createdBy: 3,
            status: 'ativo',
            createdAt: new Date('2024-02-12T16:00:00').toISOString(),
            updatedAt: new Date('2024-02-12T16:00:00').toISOString(),
        },
        {
            congregationId: 1,
            title: 'Retiro Espiritual de Mulheres',
            description: 'Retiro de três dias com pregações, workshops e momentos de oração. Tema: "Mulheres de Fé". Inclui hospedagem e alimentação.',
            startDate: '2024-03-15',
            startTime: '14:00',
            endDate: '2024-03-17',
            endTime: '16:00',
            location: 'Chácara Bethel - Bragança Paulista',
            mediaUrl: null,
            mediaType: null,
            category: 'retiro',
            attendance: null,
            createdBy: 1,
            status: 'ativo',
            createdAt: new Date('2024-02-01T09:00:00').toISOString(),
            updatedAt: new Date('2024-02-01T09:00:00').toISOString(),
        },
        {
            congregationId: 2,
            title: 'Escola Dominical',
            description: 'Aulas de escola dominical para todas as idades. Classes separadas por faixas etárias com professores capacitados.',
            startDate: '2024-03-10',
            startTime: '09:00',
            endDate: '2024-03-10',
            endTime: '10:00',
            location: 'Congregação Jarinu',
            mediaUrl: null,
            mediaType: null,
            category: 'infantil',
            attendance: 38,
            createdBy: 2,
            status: 'ativo',
            createdAt: new Date('2024-02-08T11:00:00').toISOString(),
            updatedAt: new Date('2024-02-08T11:00:00').toISOString(),
        },
        {
            congregationId: 1,
            title: 'Culto de Oração e Jejum',
            description: 'Manhã dedicada à oração e busca pela presença de Deus. Momento de intercessão pela igreja, família e nação.',
            startDate: '2024-03-13',
            startTime: '06:00',
            endDate: '2024-03-13',
            endTime: '08:00',
            location: 'Templo Central - Sede Atibaia',
            mediaUrl: null,
            mediaType: null,
            category: 'culto',
            attendance: 95,
            createdBy: 1,
            status: 'ativo',
            createdAt: new Date('2024-02-05T15:30:00').toISOString(),
            updatedAt: new Date('2024-02-05T15:30:00').toISOString(),
        },
        {
            congregationId: 1,
            title: 'Evangelismo na Praça Central',
            description: 'Ação evangelística com distribuição de folhetos, testemunhos e ministrações. Venha compartilhar o amor de Cristo com nossa cidade.',
            startDate: '2024-03-16',
            startTime: '15:00',
            endDate: '2024-03-16',
            endTime: '18:00',
            location: 'Praça Central de Atibaia',
            mediaUrl: null,
            mediaType: null,
            category: 'evangelismo',
            attendance: null,
            createdBy: 3,
            status: 'ativo',
            createdAt: new Date('2024-02-14T13:00:00').toISOString(),
            updatedAt: new Date('2024-02-14T13:00:00').toISOString(),
        },
        {
            congregationId: 2,
            title: 'Culto de Ações de Graças',
            description: 'Culto especial de gratidão a Deus pelas bênçãos recebidas. Momento de testemunhos e louvor.',
            startDate: '2024-03-24',
            startTime: '18:00',
            endDate: '2024-03-24',
            endTime: '20:00',
            location: 'Congregação Jarinu',
            mediaUrl: null,
            mediaType: null,
            category: 'culto',
            attendance: 72,
            createdBy: 2,
            status: 'ativo',
            createdAt: new Date('2024-02-18T10:00:00').toISOString(),
            updatedAt: new Date('2024-02-18T10:00:00').toISOString(),
        },
        {
            congregationId: 1,
            title: 'Conferência de Avivamento',
            description: 'Conferência especial com pregadores convidados de todo Brasil. Três noites de ministrações poderosas e transformadoras.',
            startDate: '2024-04-05',
            startTime: '19:00',
            endDate: '2024-04-07',
            endTime: '21:30',
            location: 'Templo Central - Sede Atibaia',
            mediaUrl: null,
            mediaType: null,
            category: 'conferencia',
            attendance: null,
            createdBy: 1,
            status: 'ativo',
            createdAt: new Date('2024-02-20T08:00:00').toISOString(),
            updatedAt: new Date('2024-02-20T08:00:00').toISOString(),
        },
        {
            congregationId: 2,
            title: 'Ministério Infantil - Atividades Recreativas',
            description: 'Tarde de brincadeiras, histórias bíblicas e lanche para as crianças. Equipe preparada com atividades lúdicas e ensino da Palavra.',
            startDate: '2024-03-23',
            startTime: '14:00',
            endDate: '2024-03-23',
            endTime: '17:00',
            location: 'Congregação Jarinu',
            mediaUrl: null,
            mediaType: null,
            category: 'infantil',
            attendance: 52,
            createdBy: 3,
            status: 'ativo',
            createdAt: new Date('2024-02-16T12:00:00').toISOString(),
            updatedAt: new Date('2024-02-16T12:00:00').toISOString(),
        },
    ];

    await db.insert(events).values(sampleEvents);
    
    console.log('✅ Events seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});