import { db } from '@/db';
import { members } from '@/db/schema';

async function main() {
    const sampleMembers = [
        {
            congregationId: 1,
            name: 'Pastor João Silva',
            cpf: '123.456.789-00',
            rg: '12.345.678-9',
            birthDate: '1975-03-15',
            age: 49,
            sex: 'masculino',
            email: 'joao.silva@ipcecma.com.br',
            phone: '(11) 98888-1111',
            address: 'Rua das Igrejas, 50',
            cep: '12940-000',
            neighborhood: 'Centro',
            city: 'Atibaia',
            state: 'SP',
            position: 'pastor',
            baptismDate: '1990-12-25',
            memberSince: '2010-01-10',
            photoUrl: null,
            status: 'ativo',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            congregationId: 1,
            name: 'Carlos Eduardo Santos',
            cpf: '234.567.890-11',
            rg: '23.456.789-0',
            birthDate: '1980-07-22',
            age: 44,
            sex: 'masculino',
            email: 'carlos.santos@gmail.com',
            phone: '(11) 98888-2222',
            address: 'Av. Jerônimo de Camargo, 120',
            cep: '12940-010',
            neighborhood: 'Alvinópolis',
            city: 'Atibaia',
            state: 'SP',
            position: 'diacono',
            baptismDate: '2000-04-15',
            memberSince: '2012-06-20',
            photoUrl: null,
            status: 'ativo',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            congregationId: 1,
            name: 'Maria Aparecida Costa',
            cpf: '345.678.901-22',
            rg: '34.567.890-1',
            birthDate: '1992-11-05',
            age: 32,
            sex: 'feminino',
            email: 'maria.costa@outlook.com',
            phone: '(11) 98888-3333',
            address: 'Rua Visconde do Rio Branco, 300',
            cep: '12940-020',
            neighborhood: 'Centro',
            city: 'Atibaia',
            state: 'SP',
            position: 'membro',
            baptismDate: '2015-08-10',
            memberSince: '2015-07-01',
            photoUrl: null,
            status: 'ativo',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            congregationId: 2,
            name: 'Paulo Roberto Lima',
            cpf: '456.789.012-33',
            rg: '45.678.901-2',
            birthDate: '1985-05-18',
            age: 39,
            sex: 'masculino',
            email: 'paulo.lima@yahoo.com.br',
            phone: '(11) 98888-4444',
            address: 'Rua São José, 75',
            cep: '13240-000',
            neighborhood: 'Centro',
            city: 'Jarinu',
            state: 'SP',
            position: 'lider-celula',
            baptismDate: '2005-09-20',
            memberSince: '2014-03-15',
            photoUrl: null,
            status: 'ativo',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            congregationId: 2,
            name: 'Ana Paula Ferreira',
            cpf: '567.890.123-44',
            rg: '56.789.012-3',
            birthDate: '1995-09-30',
            age: 29,
            sex: 'feminino',
            email: 'ana.ferreira@gmail.com',
            phone: '(11) 98888-5555',
            address: 'Av. das Palmeiras, 180',
            cep: '13240-010',
            neighborhood: 'Jardim Alvorada',
            city: 'Jarinu',
            state: 'SP',
            position: 'membro',
            baptismDate: '2018-11-25',
            memberSince: '2018-10-01',
            photoUrl: null,
            status: 'ativo',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
    ];

    await db.insert(members).values(sampleMembers);
    
    console.log('✅ Members seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});